// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditUserDescriptionController from "./edit_user_description_controller"
application.register("edit-user-description", EditUserDescriptionController)

import EditUserDetailsController from "./edit_user_details_controller"
application.register("edit-user-details", EditUserDetailsController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
