// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConnectionsController from "./connections_controller"
application.register("connections", ConnectionsController)

import DisableEndDateController from "./disable_end_date_controller"
application.register("disable-end-date", DisableEndDateController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
