version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: dev_community_postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:7.0-alpine
    container_name: dev_community_redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
    name: dev_community_postgres
  redis:
    name: dev_community_redis
